# -*- coding: utf-8 -*-
"""Social Media Finder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12p4aZIk2kSqD9y2w9G-2vu-hj9f7TIq8
"""

import pandas as pd

# ✅ Just edit this list — length can be 5 or 500, everything else adjusts automatically
talent_names = [
    "Alicia Menendez"
    # ...add more freely here
]

# Define platform columns
platforms = ["Facebook", "Instagram", "X", "TikTok", "YouTube"]

# Build DataFrame dynamically
talent_data = {"Talent Name": talent_names}
for p in platforms:
    talent_data[p] = [""] * len(talent_names)

talent_df = pd.DataFrame(talent_data)
print(f"✅ Talent list initialized with {len(talent_df)} rows.")
talent_df.head()

# ================== INSTALLS ==================
!pip -q install openpyxl

# ================== IMPORTS ==================
import pandas as pd
import requests, re, time, random
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from google.colab import files

# ================== CONFIG ==================
CSE_KEY = "AIzaSyBQSW64LiXwowmaJsySN63wuW80U0jgqLo"
CSE_CX  = "b072d5bee5e3747eb"

RESULTS_PER_QUERY = 10
MAX_WORKERS = 5
REQUEST_DELAY_BETWEEN_TALENTS = (0.12, 0.25)

PLATFORMS = {
    "Facebook": ["facebook.com"],
    "Instagram": ["instagram.com"],
    "X": ["x.com", "twitter.com"],
    "TikTok": ["tiktok.com"],
    "YouTube": ["youtube.com"],
}

# ================== VALIDATE talent_df ==================
try:
    assert 'talent_df' in globals(), "❌ talent_df is not defined. Please run the cell above first."
    assert 'Talent Name' in talent_df.columns, "❌ 'Talent Name' column missing in talent_df."
    print(f"✅ Found talent_df with {len(talent_df)} entries.")
except AssertionError as e:
    raise SystemExit(e)

# Ensure platform columns exist
for col in PLATFORMS.keys():
    if col not in talent_df.columns:
        talent_df[col] = ""

# ================== URL SCORING ==================
_PATTERNS = {
    "Instagram": {
        "prefer": [re.compile(r"^https?://(www\.)?instagram\.com/[^/]+/?$")],
        "avoid": ["/explore/", "/reel/", "/reels/", "/p/", "/stories/", "/tags/", "/locations/"],
    },
    "X": {
        "prefer": [re.compile(r"^https?://(www\.)?(x\.com|twitter\.com)/[^/]+/?$")],
        "avoid": ["/hashtag/", "/search?", "/i/spaces", "/compose/", "/home"],
    },
    "TikTok": {
        "prefer": [re.compile(r"^https?://(www\.)?tiktok\.com/@[^/]+/?$")],
        "avoid": ["/tag/", "/music/", "/discover", "/foryou"],
    },
    "YouTube": {
        "prefer": [
            re.compile(r"^https?://(www\.)?youtube\.com/@[^/]+/?$"),
            re.compile(r"^https?://(www\.)?youtube\.com/channel/[^/]+/?$"),
            re.compile(r"^https?://(www\.)?youtube\.com/c/[^/]+/?$"),
        ],
        "avoid": ["/watch?", "/results?", "/shorts/", "/playlist?"],
    },
    "Facebook": {
        "prefer": [re.compile(r"^https?://(www\.)?facebook\.com/(pages/)?[^/?#]+/?$")],
        "avoid": ["/public/", "/hashtag/", "/groups/", "/events/", "/marketplace/"],
    },
}

def _score_url(platform: str, url: str) -> int:
    if not isinstance(url, str) or not url:
        return -10
    s = 0
    for bad in _PATTERNS[platform]["avoid"]:
        if bad in url:
            s -= 5
    for rgx in _PATTERNS[platform]["prefer"]:
        if rgx.match(url):
            s += 10
            break
    if "?" not in url and "#" not in url:
        s += 1
    return s

# ================== QUERY BUILDING ==================
def _build_queries(talent: str, domains: list[str], platform: str) -> list[str]:
    qs = []
    for d in domains:
        qs.append(f'site:{d} "{talent}" official')
        qs.append(f'site:{d} "{talent}"')
    qs.append(f'"{talent}" {platform} official')
    qs.append(f'"{talent}" {platform}')
    return qs

# ================== GOOGLE CSE SEARCH ==================
def cse_search(query: str, num: int = 10) -> list[dict]:
    url = "https://www.googleapis.com/customsearch/v1"
    params = {
        "key": CSE_KEY,
        "cx": CSE_CX,
        "q": query,
        "num": min(num, 10),
        "safe": "active",
        "hl": "en",
        "gl": "us",
    }
    r = requests.get(url, params=params, timeout=20)
    r.raise_for_status()
    data = r.json()
    items = data.get("items", []) or []
    return [{"position": i+1, "link": it.get("link")} for i, it in enumerate(items)]

# ================== PICK BEST ==================
def _pick_best(candidates: list[dict], domains: list[str], platform: str, domain_filter_active: bool) -> str:
    best_link, best_score = None, -999
    def domain_ok(u: str) -> bool:
        return any(d in (u or "") for d in domains) if domains else True

    for r in candidates:
        url = r.get("link")
        if not url:
            continue
        if domain_filter_active and domains and not domain_ok(url):
            continue
        s = _score_url(platform, url)
        if r.get("position") == 1:
            s += 2
        if s > best_score:
            best_link, best_score = url, s
    return best_link or "Not Found"

# ================== LOOKUP FUNCTION ==================
def search_one(talent: str, platform: str, domains: list[str]) -> tuple[str, str]:
    talent = re.sub(r"\s+", " ", (talent or "").strip().strip('"').strip("'"))
    queries = _build_queries(talent, domains, platform)

    for q in queries:
        try:
            results = cse_search(q, num=RESULTS_PER_QUERY)
            domain_filter = q.startswith("site:")
            link = _pick_best(results, domains, platform, domain_filter)
            if link != "Not Found":
                return platform, link
        except Exception as e:
            print(f"⚠️ CSE error [{platform}] for '{talent}': {e}")
            time.sleep(0.2)
    return platform, "Not Found"

def lookup_row(idx: int, row: pd.Series):
    name = str(row.get("Talent Name", "") or "").strip()
    if not name:
        return
    futures = {}
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
        for platform, domains in PLATFORMS.items():
            current = row.get(platform, "")
            if isinstance(current, str) and current.strip():
                continue
            futures[ex.submit(search_one, name, platform, domains)] = platform
        for fut in as_completed(futures):
            platform, link = fut.result()
            talent_df.at[idx, platform] = link

# ================== RUN ==================
rows = len(talent_df)
print(f"Processing {rows} row(s)…")
for idx, row in talent_df.iterrows():
    lookup_row(idx, row)
    time.sleep(random.uniform(*REQUEST_DELAY_BETWEEN_TALENTS))
    if (idx + 1) % 10 == 0:
        print(f"…{idx + 1}/{rows} done")

# ================== SAVE + DOWNLOAD ==================
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
OUTPUT_FILE = f"Talent_Social_Lookup_{timestamp}.xlsx"
talent_df.to_excel(OUTPUT_FILE, index=False)
print(f"\n✅ Saved: {OUTPUT_FILE}")

files.download(OUTPUT_FILE)